### ISSUE TITLE
Residue mutations fail when PDB files contain repeated chain entries

### ISSUE THREAD

**Issue by jchodera** [pandegroup/pdbfixer#109]
The following script
```
from pdbfixer import PDBFixer
from simtk.openmm.app import PDBFile
fixer = PDBFixer(pdbid='1OL5')
fixer.findMissingResidues()
fixer.findMissingAtoms()
fixer.addMissingAtoms()
fixer.applyMutations(['TPO-287-THR','TPO-288-THR'], 'A')
```
fails with the error
```
Traceback (most recent call last):
  File "pdbfix1OL5.py", line 10, in <module>
    fixer.applyMutations(['TPO-287-THR','TPO-288-THR'], 'A')
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/pdbfixer-1.2-py2.7.egg/pdbfixer/pdbfixer.py", line 756, in applyMutations
    index = resSeq_to_index[resSeq]
KeyError: 287
```
This appears to be due to the fact that the PDB file contains chain A (protein), chain B (another protein), and then another chain A (solvent) and chain B (solvent).  This causes the `resSeq_to_index` dict to be populated with only the *last* chain `A` (solvent) rather than all residues belonging to chain `A`:
```
resSeq_to_index {2048: 54, 2049: 55, 2050: 56, 2051: 57, 2052: 58, 2053: 59, 2054: 60, 2055: 61, 2056: 62, 2057: 63, 2058: 64, 2059: 65, 2060: 66, 2061: 67, 2062: 68, 2063: 69, 2064: 70, 2065: 71, 2066: 72, 2067: 73, 2068: 74, 2069: 75, 2070: 76, 2071: 77, 2072: 78, 2073: 79, 2074: 80, 2075: 81, 2076: 82, 2077: 83, 2078: 84, 2079: 85, 2080: 86, 2081: 87, 2082: 88, 2083: 89, 2084: 90, 2085: 91, 2086: 92, 2087: 93, 2088: 94, 2089: 95, 2090: 96, 2091: 97, 2092: 98, 2093: 99, 2094: 100, 2095: 101, 2096: 102, 2097: 103, 2098: 104, 2099: 105, 2100: 106, 2101: 107, 2102: 108, 2103: 109, 2104: 110, 2105: 111, 2106: 112, 2107: 113, 2108: 114, 2109: 115, 2110: 116, 2111: 117, 2112: 118, 2113: 119, 2114: 120, 2115: 121, 2116: 122, 2117: 123, 2118: 124, 2119: 125, 2120: 126, 2121: 127, 2122: 128, 2123: 129, 2124: 130, 2125: 131, 2126: 132, 2127: 133, 2128: 134, 2129: 135, 2130: 136, 2131: 137, 2132: 138, 1388: 0, 1389: 1, 1390: 2, 1391: 3, 1392: 4, 1393: 5, 1394: 6, 2001: 7, 2002: 8, 2003: 9, 2004: 10, 2005: 11, 2006: 12, 2007: 13, 2008: 14, 2009: 15, 2010: 16, 2011: 17, 2012: 18, 2013: 19, 2014: 20, 2015: 21, 2016: 22, 2017: 23, 2018: 24, 2019: 25, 2020: 26, 2021: 27, 2022: 28, 2023: 29, 2024: 30, 2025: 31, 2026: 32, 2027: 33, 2028: 34, 2029: 35, 2030: 36, 2031: 37, 2032: 38, 2033: 39, 2034: 40, 2035: 41, 2036: 42, 2037: 43, 2038: 44, 2039: 45, 2040: 46, 2041: 47, 2042: 48, 2043: 49, 2044: 50, 2045: 51, 2046: 52, 2047: 53}
```

**Comment by jchodera** [comment]
I think I've fixed it in #110.  I've also added a test for this case.

This is another feature where a more user-friendly API for `Topology` that let us look things up or slice by `chainid` and `resid` more easily (e.g. using ParmEd `Structure`-like capabilities) would be very helpful.
