### ISSUE TITLE
AttributeError: 'Chain' object has no attribute 'id'

### ISSUE THREAD

**Issue by leeping** [pandegroup/pdbfixer#89]
I observed this when trying to download PDB ID 1YRF.  Going back to revision `19a9581015335e994b4f3c2840a6c37388253997` fixed it.

```
leeping@leeping:~/src/pdbfixer$ pdbfixer
PDBFixer running: http://localhost:8000 
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 34441)
Traceback (most recent call last):
  File "/home/leeping/local/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/leeping/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/leeping/local/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/home/leeping/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/leeping/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/leeping/local/lib/python2.7/site-packages/pdbfixer-1.0-py2.7.egg/pdbfixer/uiserver.py", line 29, in do_POST
    self.invokeCallback(parameters)
  File "/home/leeping/local/lib/python2.7/site-packages/pdbfixer-1.0-py2.7.egg/pdbfixer/uiserver.py", line 41, in invokeCallback
    callback[path](parameters, self)
  File "/home/leeping/local/lib/python2.7/site-packages/pdbfixer-1.0-py2.7.egg/pdbfixer/ui.py", line 73, in startPageCallback
    displayDeleteChainsPage()
  File "/home/leeping/local/lib/python2.7/site-packages/pdbfixer-1.0-py2.7.egg/pdbfixer/ui.py", line 147, in displayDeleteChainsPage
    table += '    <tr><td>%s</td><td>%d</td><td>%s</td><td><input type="checkbox" name="include%d" checked></td></tr>\n' % (chain.id, len(residues), content, i)
AttributeError: 'Chain' object has no attribute 'id'
----------------------------------------
```

**Comment by peastman** [comment]
If you're going to use the last code from the PDBFixer repository, you need the latest code from the OpenMM repository as well.

**Comment by leeping** [comment]
Ah, got it. Thanks :)

**Comment by sgarturo** [comment]
I get a similar error going through python.  Using 1ENH from the pdb and the block of script in the manual (first line findMissingResidues), I get from the first line
AttributeError: 'Residue' object has no attribute 'id'

I installed PDFFixer on 7/2/2015 and am using OpenMM precompiled binaries for Windows
OpenMM-6.2.0-WindowsVC10.zip (10240 kB)	binary	Windows	Dec 04, 2014

Do I have a mismatch between PDFFixer and OpenMM?

**Comment by jchodera** [comment]
> Do I have a mismatch between PDFFixer and OpenMM?

Yep.  The current git head of `pdbfixer` requires OpenMM 6.3, which is in beta now but isn't released in binary package form yet.

I think installing the `pdbfixer 1.1` release will work for you, since I believe that requires OpenMM 6.2:
https://github.com/pandegroup/pdbfixer/releases/tag/v1.1

**Comment by jchodera** [comment]
I think this can be closed.

**Comment by sgarturo** [comment]
Agreed. The fix provided worked.

Sorry for not getting back to you sooner
